[allowlist]
description = "Allowlisted files"
paths = ['package-lock.json$', 'yarn.lock$', 'pnpm-lock.yaml$']

[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(?:key|token|secret)[\w-]*[=:]["'][A-Za-z0-9+/]{32,}["']'''
tags = ["key", "API", "generic"]

[[rules]]
id = "generic-secret"
description = "Generic Secret"
regex = '''(?i)(?:password|secret)[\w-]*[=:]["'][A-Za-z0-9+/]{16,}["']'''
tags = ["key", "secret"]
